title: Awesomebots
author: ben kline
email: info@awesomebots.org
phone: 208-409-3025
cta:
  phrase: Learn More #ie sign-up
  url: /about
description: > # this means to ignore newlines until next entry

# social links
# twitter_username:
# github_username:
# rss: rss
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# linkedin_username:
# pinterest_username:
# youtube_username:
# googleplus_username:

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

#google:
#  analytics:
#  confirm_ownership:

show_excerpts: false # set to true to show excerpts on the homepage

date_format: "%b %-d, %Y"

# add the path to the pages in order as they should show up in the header
header_pages:
 - about.md
 - blog.md

# add the path to the auth pages - call to action button should be second
auth_pages:
- login.md
- signup.md

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - semantic
  - package.json
  - node_modules
  - gulpfile.js
